name: azure_communication_calling
description: "Azure Communication Calling for Flutter"
version: 1.0.0
homepage: https://github.com/ARASHz4/azure_communication_calling

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.arashz4.azure_communication_calling
        pluginClass: AzureCommunicationCallingPlugin
      ios:
        pluginClass: AzureCommunicationCallingPlugin
